# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

omua_to_R <- function(X, Y, W, lambda, endspan, minspan, degree, nk, penalty, trace, thresh) {
    invisible(.Call(`_Oumuamua_omua_to_R`, X, Y, W, lambda, endspan, minspan, degree, nk, penalty, trace, thresh))
}

